#! /bin/sh
# /etc/init.d/sound_drive_boot

### BEGIN INIT INFO
# Provides: sound_drive_boot
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 5
# Default-Stop: 0 1 2 3 4 6
# Short-Description: Start SoundDrive at boot time (created be Ofek)
# Description: Start SoundDrive at boot time (created by Ofek)
### END INIT INFO

USER=pi
HOME=/home/pi

export USER HOME

case "$1" in
 start)
  echo "Starting SoundDrive"
  su - $USER -c "sudo killall python; sudo killall mplayer; sudo killall hcidump; cd /home/pi/ofek/SoundDrive; echo \"DATE: $(date), RUNLEVEL: $(runlevel)\" > output; python Main.py >> output 2>$1 &"
  ;;

 stop)
  echo "Stopping SoundDrive"
  sudo killall python
  sudo killall mplayer
  sudo killall hcidump
  ;;

 *)
  echo "Usage: /etc/init.d/sound_drive_boot {start|stop}"
  exit 1
  ;;
esac

exit 0
